#!/usr/bin/env bash
# This script displays:`To infinity and beyond` infinite times; with a `sleep 2` between each iteration; and `I am invincible!!!` when receiving a `SIGTERM` signal.
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
