#!/usr/bin/env bash
#The script displays numbers from 1 to 100. It displays FizzBuzz when the number is a multiple of 3 and 5; Fizz when the number is a multiple of 3, and Buzz when the number is a multiple of 5.

for (( i=1; i<=100; i++ ))
do
    if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ]
    then
	printf "FizzBuzz\n"
    elif [ $((i%3)) == 0 ]
    then
	printf "Fizz\n"
    elif [ $((i%5)) == 0 ]
    then
	printf "Buzz\n"
    else
        printf "%i\n" "$i"
    fi
done
