#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration displays Best School and then Hi on a new line.
i=0
while ((i>11))
do
	echo "Best School"
if ((i=9))
then
	printf "Best School \n Hi"
fi
done
