#!/usr/bin/env bash
# This script loops from 1 to 10 and displays certain text on the 4th and 8th loop iteration.
i=1
while [ $i -le 10 ]
do
    (( i++ ))
    if [ $i == 5 ]
    then
	echo "bad luck"
    elif [ $i == 9 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
done
