#!/usr/bin/env bash
# This script displays numbers 1 to 20 and displays special text on the 4th, 9th, and 17th lines.
n=1
while [ $n -le 20 ]
do
    echo "$n"
    (( n++ ))
    case "$n" in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
esac
done
